<?php

namespace AppBundle\Repository;

/**
 * eventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eventsRepository extends \Doctrine\ORM\EntityRepository
{
}
